Optimized api
NanoMichael/cLaTeXMath pull request #111
Opened 2022-03-01 17:11 UTC by NanoMichael

2022-03-03 19:38 UTC, sp1ritCS requested changes

2022-03-03 19:38 UTC, sp1ritCS commented on lib/meson.build
> +		'tinytexconfig.h'
This fails, as tinytexconfig.h does not exist. You need to assign a lside variable from the configure_file that configures the `tinytexconfig.h.in` and put the var in the install_headers array

2022-03-03 19:44 UTC, sp1ritCS requested changes

2022-03-03 19:44 UTC, sp1ritCS commented on lib/unimath/uni_font.cpp
> -void FontContext::addMathFont(const FontSrc& src) {
`test/env/test_env.cpp` still has a reference to `FontContext::addMathFont`

2022-03-05 16:17 UTC, NanoMichael commented
close #105 #106

2022-03-05 16:17 UTC, merged